# Generated by Django 4.2.7 on 2023-12-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamerTechArg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placasdevideo',
            old_name='anio',
            new_name='año',
        ),
    ]
